// Classes and structures being serialized

// Generated by ProtocolBuffer
// - a pure c# code generation implementation of protocol buffers
// Report bugs to: https://silentorbit.com/protobuf/

// DO NOT EDIT
// This file will be overwritten when CodeGenerator is run.
// To make custom modifications, edit the .proto file and add //:external before the message line
// then write the code and the changes in a separate file.
using System;
using System.Collections.Generic;

namespace Example
{
    /// <summary>
    /// <para>option java_outer_classname = "LivePB";</para>
    /// <para> 11001</para>
    /// <para>------------------------------------------------------房间外的</para>
    /// </summary>
    public partial class CSCreateLiveRoom
    {
    }

    public partial class SCCreateLiveRoom
    {
        public int RoomId { get; set; }

        /// <summary> 房间id</summary>
        public string Host { get; set; }

        public int Port { get; set; }

    }

    public partial class CSGetRoomList
    {
    }

    public partial class SCGetRoomList
    {
        public List<Example.PBRoomInfo> RoomInfo { get; set; }

    }

    public partial class PBRoomInfo
    {
        public int RoomId { get; set; }

        public int Member { get; set; }

        /// <summary> 人数</summary>
        public int Status { get; set; }

        /// <summary> 状态</summary>
        public string Host { get; set; }

        /// <summary> 状态</summary>
        public int Port { get; set; }

    }

    /// <summary>
    /// <para>------------------------------------------------------房间里面的</para>
    /// <para> 下面在时room中的</para>
    /// </summary>
    public partial class CSStart
    {
    }

    public partial class SCStart
    {
    }

    public partial class CSMoveTo
    {
        public float Direction { get; set; }

    }

    public partial class SCMoveTo
    {
        public Example.PBStatus Status { get; set; }

    }

    public partial class CSAttack
    {
    }

    public partial class SCAttack
    {
    }

    public partial class CSSetRobot
    {
        public int Count { get; set; }

    }

    public partial class SCSetRobot
    {
    }

    /// <summary>
    /// <para>------------------------------------------------------房间里的推送信息</para>
    /// <para> 其它玩家状态，一般发生在某玩家走动，或定时发送</para>
    /// </summary>
    public partial class SCStatus
    {
        public Example.PBStatus Status { get; set; }

    }

    /// <summary> 打击结果推送事件</summary>
    public partial class SCAttackResult
    {
        public Example.PBStatus Attack { get; set; }

        /// <summary> 打击玩家的状态</summary>
        public List<Example.PBStatus> BeAttack { get; set; }

    }

    /// <summary> 广播自动死亡，自动掉血会导致死亡</summary>
    public partial class SCDie
    {
        public List<string> AccountId { get; set; }

    }

    /// <summary> 战斗结束</summary>
    public partial class SCOver
    {
        public string AccountIds { get; set; }

    }

    public partial class SCRoomChange
    {
        public Example.PBRoomInfo RoomInfo { get; set; }

    }

    /// <summary> 游戏开始的时候，推送开始消息，即所有玩家的状态</summary>
    public partial class SCStartGame
    {
        public List<Example.PBStatus> Status { get; set; }

    }

    public partial class SCRoomClose
    {
        public int Reason { get; set; }

    }

    /// <summary> 玩家状态</summary>
    public partial class PBStatus
    {
        public string AccountId { get; set; }

        /// <summary> 原位置</summary>
        public int X { get; set; }

        /// <summary> 原位置</summary>
        public int Y { get; set; }

        public float Direction { get; set; }

        /// <summary>暂时的改动，</summary>
        public int Blood { get; set; }

        public int Speed { get; set; }

    }

}
